Add BUSYBOX_CONTAINER to CONTAINERS_WITHOUT_ZYPPER
SUSE/BCI-tests pull request #110
Opened 2022-05-04 09:49 UTC by jlausuch

Reason: `tox -e all -- -n auto -k bci/bci-busybox_15.4` fails with no test runs.

2022-05-04 09:53 UTC, dcermak requested changes
you need to run `tox -e format` before the commit

2022-05-04 09:53 UTC, dcermak commented on bci_tester/data.py
> +    BUSYBOX_CONTAINER
```suggestion
    BUSYBOX_CONTAINER,
```

2022-05-04 09:54 UTC, dcermak commented
This change broke the assertion in test_metadata, I can fix that myself though if I can push to your branch.

2022-05-04 10:02 UTC, jlausuch commented
```
tox -e all -- -n auto -k bci/bci-busybox_15.4
all installed: attrs==21.4.0,dataclasses==0.8,execnet==1.9.0,filelock==3.4.1,importlib-metadata==4.8.3,iniconfig==1.1.1,packaging==21.3,pluggy==1.0.0,py==1.11.0,pyparsing==3.0.8,pytest==7.0.1,pytest-container @ git+https://github.com/dcermak/pytest_container@c64645fb097863920f147f0f4657867ac3edde92,pytest-forked==1.4.0,pytest-rerunfailures==10.2,pytest-testinfra==6.7.0,pytest-xdist==2.5.0,tomli==1.2.3,typing_extensions==4.1.1,zipp==3.6.0
all run-test-pre: PYTHONHASHSEED='839179770'
all run-test: commands[0] | pytest -vv tests/test_all.py --junitxml=/root/BCI-tests/junit_all.xml -n auto -k bci/bci-busybox_15.4
=========================================================================================================================== test session starts ============================================================================================================================
platform linux -- Python 3.6.15, pytest-7.0.1, pluggy-1.0.0 -- /root/BCI-tests/.tox/all/bin/python
cachedir: .tox/all/.pytest_cache
rootdir: /root/BCI-tests, configfile: pyproject.toml
plugins: testinfra-6.7.0, forked-1.4.0, xdist-2.5.0, rerunfailures-10.2, container-0.0.2
[gw0] linux Python 3.6.15 cwd: /root/BCI-tests
[gw1] linux Python 3.6.15 cwd: /root/BCI-tests
[gw0] Python 3.6.15 (default, Sep 15 2021, 14:20:42) [GCC]
[gw1] Python 3.6.15 (default, Sep 15 2021, 14:20:42) [GCC]
gw0 [5] / gw1 [5]
scheduling tests via LoadScheduling

tests/test_all.py::test_os_release[bci/bci-busybox:15.4 from registry.suse.de/suse/sle-15-sp4/update/cr/totest/images/bci/bci-busybox:15.4] 
tests/test_all.py::test_product[bci/bci-busybox:15.4 from registry.suse.de/suse/sle-15-sp4/update/cr/totest/images/bci/bci-busybox:15.4] 
[gw0] [ 20%] PASSED tests/test_all.py::test_os_release[bci/bci-busybox:15.4 from registry.suse.de/suse/sle-15-sp4/update/cr/totest/images/bci/bci-busybox:15.4] 
tests/test_all.py::test_glibc_present[bci/bci-busybox:15.4 from registry.suse.de/suse/sle-15-sp4/update/cr/totest/images/bci/bci-busybox:15.4] 
[gw0] [ 40%] PASSED tests/test_all.py::test_glibc_present[bci/bci-busybox:15.4 from registry.suse.de/suse/sle-15-sp4/update/cr/totest/images/bci/bci-busybox:15.4] 
tests/test_all.py::test_certificates_are_present[local-bci/bci-busybox:15.4 from registry.suse.de/suse/sle-15-sp4/update/cr/totest/images/bci/bci-busybox:15.4] 
[gw1] [ 60%] PASSED tests/test_all.py::test_product[bci/bci-busybox:15.4 from registry.suse.de/suse/sle-15-sp4/update/cr/totest/images/bci/bci-busybox:15.4] 
tests/test_all.py::test_systemd_not_installed_in_all_containers_except_init[bci/bci-busybox:15.4 from registry.suse.de/suse/sle-15-sp4/update/cr/totest/images/bci/bci-busybox:15.4] 
[gw0] [ 80%] PASSED tests/test_all.py::test_certificates_are_present[local-bci/bci-busybox:15.4 from registry.suse.de/suse/sle-15-sp4/update/cr/totest/images/bci/bci-busybox:15.4] 
[gw1] [100%] PASSED tests/test_all.py::test_systemd_not_installed_in_all_containers_except_init[bci/bci-busybox:15.4 from registry.suse.de/suse/sle-15-sp4/update/cr/totest/images/bci/bci-busybox:15.4] 

------------------------------------------------------------------------------------------------------------ generated xml file: /root/BCI-tests/junit_all.xml -------------------------------------------------------------------------------------------------------------
============================================================================================================================ 5 passed in 13.96s ============================================================================================================================
_________________________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________________________
  all: commands succeeded
  congratulations :)
```

2022-05-04 10:08 UTC, dcermak commented
@jlausuch I force pushed to your branch to fix the metadata test as well.

2022-05-05 06:49 UTC, jlausuch commented
Are we good to merge this? Pipeline failures don't seem to be related to this change.

2022-05-05 06:54 UTC, merged