Add dotnet containers to L3
SUSE/BCI-tests pull request #196
Opened 2022-12-09 09:57 UTC by grisu48

The dotnet containers for 3.1, 6, 5 and 7 should now also get the L3 support label.

2022-12-09 10:13 UTC, dcermak approved these changes

2022-12-09 10:28 UTC, grisu48 commented
Metadata failures are expected, because the released containers don't have the new label yet.

2022-12-09 13:16 UTC, dcermak requested changes
Blocking this until we have the final call from PM

2022-12-12 08:45 UTC, grisu48 commented
Following the feedback from Michal this PR is obsolete.

2022-12-12 08:45 UTC, closed without merging