BCI: fix java memory test
SUSE/BCI-tests pull request #225
Opened 2023-03-29 09:37 UTC by ilausuch

2023-03-29 09:43 UTC, dcermak requested changes

2023-03-29 09:43 UTC, dcermak commented on tests/test_openjdk.py
> +                java_params="-Xmx10M -Xlint:unchecked",
Could you please explain in the commit message what & why you have done this change?

2023-03-29 12:59 UTC, dcermak requested changes
This does not solve the problem:
```
Unrecognized option: -Xlint:unchecked
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

2023-03-30 07:44 UTC, ilausuch commented
Ready

2023-03-30 08:43 UTC, m-dati commented on tests/test_openjdk_devel.py
> +    assert "1" in testout.stderr
Also a simple suggestion, to run tidy checks in your local, before to push :-)

2023-03-30 08:57 UTC, ilausuch commented on tests/test_openjdk_devel.py
> +    assert "1" in testout.stderr
Thanks

2023-03-30 09:13 UTC, dcermak requested changes
The documentation needs to be corrected, otherwise LGTM

2023-03-30 09:13 UTC, dcermak commented on tests/test_openjdk_devel.py
> +
This description does not match what is actually being tested.

2023-03-30 09:37 UTC, dcermak approved these changes
LGTM, thank you!

2023-03-30 09:39 UTC, m-dati approved these changes

2023-03-30 10:02 UTC, merged