Remove dotnet 3.1 from testing
SUSE/BCI-tests pull request #261
Opened 2023-06-20 11:07 UTC by dirkmueller

2023-06-20 12:19 UTC, dcermak requested changes
`tests/test_metadata.py` needs to get adjusted too: 
```
tests/test_metadata.py:32: in <module>
    from bci_tester.data import DOTNET_ASPNET_3_1_CONTAINER
E   ImportError: cannot import name 'DOTNET_ASPNET_3_1_CONTAINER' from 'bci_tester.data' (/home/runner/work/BCI-tests/BCI-tests/bci_tester/data.py)
```

2023-06-21 09:07 UTC, dcermak commented
Needs a rebase on #263

2023-06-21 11:30 UTC, dirkmueller commented
neither one will succeed without the other, we would have to merge both into one PR

2023-06-21 17:11 UTC, dcermak approved these changes

2023-06-21 18:34 UTC, merged