Remove old authentications for RHEL7
SUSE/BCI-tests pull request #268
Opened 2023-07-05 13:39 UTC by grisu48

Remove the md5 authentication method for RHEL7 because it was never working as expected and is not needed anymore.

2023-07-05 14:54 UTC, dcermak requested changes
Please just completely skip these tests on rhel 7

2023-07-05 15:10 UTC, jlausuch commented
> Please just completely skip these tests on rhel 7

it has been done already in openqa level.

2023-07-05 15:14 UTC, merged

2023-07-05 15:14 UTC, dcermak commented
> > Please just completely skip these tests on rhel 7
> 
> it has been done already in openqa level.

Works for me, thanks!

2023-07-06 06:39 UTC, grisu48 commented
Exactly, they have been disabled in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17364, as linked in the description. Will try to highlight that better the next time!