Initial testing for the mariadb container
SUSE/BCI-tests pull request #354
Opened 2023-12-19 23:16 UTC by dirkmueller

2023-12-21 08:52 UTC, mloviska approved these changes

2023-12-21 09:00 UTC, dcermak requested changes
`test_build` and `test_all` are broken

2023-12-21 14:17 UTC, dcermak commented on bci_tester/data.py
> +            "MARIADB_PASSWORD": MARIADB_ROOT_PASSWORD
```suggestion
            "MARIADB_ROOT_PASSWORD": MARIADB_ROOT_PASSWORD
```

2024-01-02 15:47 UTC, mgrossu approved these changes
LGTM

2024-01-02 19:07 UTC, ricardobranco777 approved these changes
Small suggestion. LGTM

2024-01-02 19:07 UTC, ricardobranco777 commented on tests/test_mariadb.py
> +    assert container_per_test.connection.check_output("id -un") == ("root")
```suggestion
    assert container_per_test.connection.check_output("id -un") == "root"
```

2024-01-03 18:38 UTC, dirkmueller commented
(need to work on docker failures)

2024-01-08 14:04 UTC, dcermak commented on tests/test_mariadb.py
> +    assert auto_container.connection.run_expect([0], "ps")
You don't really need this, if the container does not launch, then the test setup will fail.

2024-01-09 16:26 UTC, merged