Add tests for the Spack container
SUSE/BCI-tests pull request #450
Opened 2024-04-11 05:57 UTC by e4t

This is an initial implementation.

Unfortunately, a lot of the pytest_container 'goodness' was not usable to test the Spack container:

In order to test whether sending a Spack command directly to the container works, it needs to be launched:
 `podman run --rm <spack_container> <spack_command>`
 However, when running:
   container.connection.check_output()
a command will be sent to a via
 `podman exec <containerID> sh -c ...`
which will use not be able to run a Spack command.

Furthermore, we cannot use the MultiStageBuild.build() interface as the simplistic substitue() replacement will choke on '$..' shell constructs.

I'd suggest to merge this test into a separate branch and address issues there before merging  to main.

2024-04-11 06:51 UTC, dirkmueller commented
> In order to test whether sending a Spack command directly to the container works, it needs to be launched: `podman run --rm <spack_container> <spack_command>` However, when running: container.connection.check_output() a command will be sent to a via `podman exec <containerID> sh -c ...` which will use not be able to run a Spack command.

not a great way of doing it, but you can copy the method from here: 

https://github.com/SUSE/BCI-tests/blob/main/tests/test_helm.py#L12

2024-04-11 07:13 UTC, e4t commented
> > In order to test whether sending a Spack command directly to the container works, it needs to be launched: `podman run --rm <spack_container> <spack_command>` However, when running: container.connection.check_output() a command will be sent to a via `podman exec <containerID> sh -c ...` which will use not be able to run a Spack command.
> 
> not a great way of doing it, but you can copy the method from here:
> 
> https://github.com/SUSE/BCI-tests/blob/main/tests/test_helm.py#L12

not sure if you've seen the patch, but this was pretty much what I did:
https://github.com/e4t/BCI-tests/blob/238d877309efb46d044da5ec0e9cf9554deb0cc6/tests/test_spack.py#L60-L65
and:
https://github.com/e4t/BCI-tests/blob/238d877309efb46d044da5ec0e9cf9554deb0cc6/tests/test_spack.py#L99-L106
The difference being that this code uses `check_output()` while I use `run_expect()` which gives me a finer control over the container command return value: `check_output()` accepts 0 and 1.

2024-05-02 19:44 UTC, dcermak commented on tests/test_spack.py
> +# from pytest_container.build import MultiStageBuild
```suggestion
```

2024-05-02 19:46 UTC, dcermak commented on tests/test_spack.py
> +    # )
```suggestion
```

2024-05-02 19:47 UTC, dcermak commented on tests/test_spack.py
> +    """Check if Spack Container allows to build an application container"""
Please explain in more detail what you're doing here

2024-05-05 13:17 UTC, dcermak commented on tests/test_spack.py
> +    and finally tests whether the zsh in the resulting container is can be
```suggestion
    and finally tests whether the zsh in the resulting container can be
```

2024-05-05 13:18 UTC, dcermak commented on tests/test_spack.py
> +from bci_tester.runtime_choice import PODMAN_SELECTED
```suggestion
```

2024-05-05 13:20 UTC, dcermak commented on tests/test_spack.py
> +# from pytest_container.container import Container
```suggestion
```

2024-05-05 13:20 UTC, dcermak commented on tests/test_spack.py
> +)
```suggestion
@pytest.mark.parametrize(
    "container",
    SPACK_CONTAINERS,
    indirect=True,
)
```

2024-05-05 13:24 UTC, dcermak requested changes
Fails at the moment:
```
==> Error: `spack env activate` requires Spack's shell support.
  
  To set up shell support, run the command below for your shell.
  
  For bash/zsh/sh:
    . /usr/share/spack/setup-env.sh
  
  For csh/tcsh:
    source /usr/share/spack/setup-env.csh
  
  For fish:
    source /usr/share/spack/setup-env.fish
  
  For Windows batch:
    /usr/bin\spack_cmd.bat
  
  For PowerShell:
    /usr/share/spack\setup-env.ps1
  
  Or, if you do not want to use shell support, run one of these instead:
  
      eval `spack env activate --sh   [...]`  # bash/zsh/sh
      eval `spack env activate --csh  [...]`  # csh/tcsh
      eval `spack env activate --fish [...]`  # fish
      eval `spack env activate --bat  [...]`  # batch
      eval `spack env activate --pwsh [...]`  # powershell
  
  If you have already set up Spack's shell support but still receive
  this message, please make sure to call Spack via the `spack` command
  without any path components (such as `bin/spack`).
  
==> Error: install requires a package argument or active environment

Did you mean to install using the `spack.yaml` in this directory? Try: 
    spack env activate .
    spack install
  OR
    spack --env . install
```

2024-05-07 17:14 UTC, dirkmueller commented
> Fails at the moment:

this is fixed now (again)

2024-05-08 06:24 UTC, dcermak approved these changes

2024-05-08 06:24 UTC, merged