Provide the IBS certificate for checking out the disturl
SUSE/BCI-tests pull request #588
Opened 2024-09-10 06:00 UTC by dcermak

This test would fail for hosts that don't have internal CA installed, so let's just ship it

[CI:TOXENVS] metadata

2024-09-11 20:20 UTC, dirkmueller requested changes
what are you trying to fix? there is no public access on IBS so this doesn't make any sense. 

and there is already a skip of the test for IBS..
https://github.com/SUSE/BCI-tests/pull/588/files#diff-f49ce5cf2ce23f6922b7add17ca149482d190f1c2b5892c5d1d55a28497c5556R468-R470

2024-09-12 06:41 UTC, dcermak commented
> what are you trying to fix? there is no public access on IBS so this doesn't make any sense.

I saw a failure in openQA where one of the hosts tried to read the data from IBS, but got a certificate error (and yes, I of course forgot to save the link)

2024-09-17 06:18 UTC, dcermak commented
> what are you trying to fix? there is no public access on IBS so this doesn't make any sense.

Found a problematic test run in openQA: https://openqa.suse.de/tests/15452302#step/_root_BCI-tests_metadata_/6

2024-09-17 08:42 UTC, alexandrevicenzi approved these changes

2024-09-20 13:38 UTC, merged