Test for proper oci.image.base.name/digest annotation
SUSE/BCI-tests pull request #604
Opened 2024-09-30 11:28 UTC by dirkmueller

[CI:TOXENVS] metadata

2024-09-30 12:03 UTC, alexandrevicenzi approved these changes

2024-09-30 12:05 UTC, alexandrevicenzi requested changes
Some tests seem to fail because the tags are not set, please check it.

2024-09-30 14:17 UTC, dirkmueller commented
> Some tests seem to fail because the tags are not set, please check it.

yes, I'm aware, there are a couple of issues. one is https://github.com/SUSE/BCI-dockerfile-generator/pull/1764 that is missing. 

we still should merge it imho because we're currently releasing broken containers.

2024-09-30 14:19 UTC, dirkmueller commented on tests/test_metadata.py
> +    assert base_name.startswith("registry.suse.com/")
yeah good point. we have the version check already elsewhere though (in test/all), but we can check it here as well, it is very cheap to do. will add.

2024-10-01 14:09 UTC, alexandrevicenzi approved these changes

2024-10-01 14:55 UTC, merged