Remove usage of zypper
SUSE/BCI-tests pull request #607
Opened 2024-10-05 13:40 UTC by dirkmueller

There is no zypper anymore in bci micro based containers.

2024-10-08 12:37 UTC, dcermak requested changes
This fails on Tumbleweed with:
```
0.110 /bin/sh: line 1: tar: command not found
```

You could try to use the `container_git_clone` fixture instead: https://github.com/SUSE/BCI-tests/blob/35aefbb4f8c646cc9818439601412dec4f295f9a/conftest.py#L22

2024-10-08 16:36 UTC, dirkmueller commented
> You could try to use the `container_git_clone` fixture instead:
> 
> https://github.com/SUSE/BCI-tests/blob/35aefbb4f8c646cc9818439601412dec4f295f9a/conftest.py#L22

that does the cloning at test runtime, rather than at build time of the container. if we don't want to add tar to the container on tumbleweed then I think I need to wait until the multibuild refactoring is over and make this a proper multibuild package.

2024-10-08 16:38 UTC, dirkmueller commented
see https://github.com/SUSE/BCI-dockerfile-generator/pull/1817 instead.

2024-10-09 09:43 UTC, dirkmueller commented
thanks for merging the tar change. now I'd like to get this change reviewed as otherwise the tests are broken.

2024-10-10 07:53 UTC, dcermak approved these changes

2024-10-10 07:53 UTC, merged