run all the jobs for sp7
SUSE/BCI-tests pull request #637
Opened 2024-10-31 08:36 UTC by dirkmueller

2025-01-23 13:22 UTC, grisu48 requested changes

2025-01-23 13:22 UTC, grisu48 commented on .github/workflows/ci.yaml
> -          - toxenv: all
Accidental removal?

2025-01-23 14:58 UTC, dcermak commented on .github/workflows/ci.yaml
> -          - toxenv: all
no it's not accidental, the `all` environment should be running by default already

2025-01-23 18:43 UTC, alexandrevicenzi submitted a review, later dismissed

2025-01-23 18:43 UTC, alexandrevicenzi commented on .github/workflows/ci.yaml
> -          - toxenv: all
nit: it would be nice to split into another commit with proper justification.

2025-01-28 18:08 UTC, grisu48 submitted a review, later dismissed
LGTM!

2025-01-28 18:09 UTC, grisu48 commented on .github/workflows/ci.yaml
>            - 15.5
Leap 15.5 is EOL since End of December 2024. Let's remove it as well.

2025-01-28 21:54 UTC, dirkmueller commented on .github/workflows/ci.yaml
>            - 15.5
good point, added another commit

2025-02-18 11:36 UTC, dcermak approved these changes

2025-02-18 14:22 UTC, grisu48 approved these changes

2025-02-18 14:22 UTC, merged