Skip tests that depend on the BCI repo for the LTSS container
SUSE/BCI-tests pull request #711
Opened 2024-12-20 09:06 UTC by dirkmueller

We have the LTSS container on a service pack still in general support, so a container-specific exclusion rather than merely a version based exclusion is needed.

2024-12-20 09:32 UTC, dcermak reviewed
LGTM in general, but  I think handling this in a decorator would be more obvious as that's where we generally handle skipifs

2024-12-20 11:12 UTC, dirkmueller commented
> LGTM in general, but I think handling this in a decorator would be more obvious as that's where we generally handle skipifs

it is a lot of repetition imho. anyhow, updated.

2024-12-20 15:39 UTC, m-dati commented
LGTM, but some CI checks fail

2024-12-20 20:00 UTC, dcermak approved these changes

2024-12-20 20:01 UTC, dcermak requested changes
Well, we also need to fix the remaining test (metadata for instance is red as well)

2024-12-20 20:15 UTC, dirkmueller commented
> Well, we also need to fix the remaining test (metadata for instance is red as well)

did you check the error?

> Command '['docker', 'pull', 'registry.suse.com/suse/ltss/sle15.5/bci-base:15.5']' returned non-zero exit status 1

That's because this PR is not being merged. metadata checks are green in openqa, the only thing blocking it from being erleased is this PR.

2024-12-21 13:09 UTC, dirkmueller commented
moving ahead, we need to get the container out..

2024-12-21 13:09 UTC, merged